# Generated by Django 2.0.8 on 2018-12-17 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('aid', models.IntegerField(help_text='动作id', primary_key=True, serialize=False, verbose_name='动作id')),
                ('videoRes', models.CharField(default='', help_text='视频链接', max_length=200, verbose_name='视频链接')),
                ('actionName', models.CharField(default='', help_text='动作名称', max_length=100, verbose_name='动作名称')),
                ('doItRight', models.TextField(default='', help_text='doItRight', verbose_name='doItRight')),
                ('breathing', models.TextField(default='', help_text='breathing', verbose_name='breathing')),
                ('videoSize', models.IntegerField(default=0, help_text='视频大小', verbose_name='视频大小')),
                ('imgCover', models.ImageField(default='', help_text='封面图', max_length=200, upload_to='video_cover/', verbose_name='封面图')),
                ('duration', models.IntegerField(default=30, help_text='单次时长', verbose_name='单次时长')),
                ('repeatCount', models.IntegerField(default=1, help_text='重复次数', verbose_name='重复次数')),
                ('imgLocal', models.ImageField(default='', help_text='本地地址', upload_to='', verbose_name='本地地址')),
            ],
            options={
                'verbose_name': '动作',
                'verbose_name_plural': '动作',
                'db_table': 'sport_action',
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('challengeId', models.IntegerField(help_text='课程id', primary_key=True, serialize=False, unique=True, verbose_name='课程id')),
                ('challengeName', models.CharField(help_text='课程名称', max_length=100, verbose_name='课程名称')),
                ('imgCover', models.ImageField(default='', help_text='封面图', upload_to='imgs/', verbose_name='封面图')),
                ('level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='课程等级', verbose_name='课程等级')),
                ('pgmIds', models.CharField(help_text='课程ids', max_length=150, verbose_name='课程ids')),
            ],
            options={
                'verbose_name': '挑战课程',
                'verbose_name_plural': '挑战课程',
                'db_table': 'sport_challenge',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('pgmId', models.IntegerField(help_text='课程id', primary_key=True, serialize=False, verbose_name='课程id')),
                ('programName', models.CharField(default='', help_text='课程名称', max_length=100, verbose_name='课程名称')),
                ('chargeType', models.IntegerField(choices=[(0, '免费'), (1, '收费或观看视频'), (2, '收费')], help_text='付费类型', verbose_name='付费类型')),
                ('totalTime', models.IntegerField(default=0, help_text='总时长', verbose_name='总时长')),
                ('kcal', models.IntegerField(default=0, help_text='卡路里', verbose_name='卡路里')),
                ('level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='等级', verbose_name='等级')),
                ('programDesc', models.TextField(default='', help_text='课程描述', verbose_name='课程描述')),
                ('pgmType', models.IntegerField(choices=[(0, '普通课程'), (1, '挑战课程')], help_text='课程类型', verbose_name='课程类型')),
                ('imgCover', models.ImageField(default='', help_text='封面图', max_length=200, upload_to='imgs/', verbose_name='封面图')),
                ('imgCoverBig', models.CharField(default='', help_text='封面大图', max_length=200, verbose_name='封面大图')),
                ('restIndexArray', models.CharField(default='', help_text='休息Index', max_length=100, verbose_name='休息Index')),
                ('actionIds', models.CharField(default='', help_text='课程ids', max_length=100, verbose_name='课程ids')),
                ('challenge', models.ForeignKey(blank=True, help_text='所属挑战课程', null=True, on_delete=django.db.models.deletion.CASCADE, to='sport.Challenge', verbose_name='所属挑战课程')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'db_table': 'sport_program',
            },
        ),
    ]
