# Generated by Django 2.0.8 on 2018-12-17 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionName', models.CharField(default='', help_text='动作名称', max_length=100, verbose_name='动作名称')),
                ('doItRight', models.TextField(default='', help_text='doItRight', verbose_name='doItRight')),
                ('breathing', models.TextField(default='', help_text='breathing', verbose_name='breathing')),
                ('action', models.ForeignKey(help_text='所属动作', on_delete=django.db.models.deletion.CASCADE, to='sport.Action', verbose_name='所属动作')),
            ],
            options={
                'verbose_name': '动作多语言',
                'verbose_name_plural': '动作多语言',
                'db_table': 'sport_language_action',
            },
        ),
        migrations.CreateModel(
            name='LanguageBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(help_text='语言', max_length=20, verbose_name='语言')),
            ],
            options={
                'verbose_name': '语言',
                'verbose_name_plural': '语言',
            },
        ),
        migrations.CreateModel(
            name='LanguageChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challengeName', models.CharField(help_text='课程名称', max_length=100, verbose_name='课程名称')),
                ('challenge', models.ForeignKey(help_text='所属挑战课程', on_delete=django.db.models.deletion.CASCADE, to='sport.Challenge', verbose_name='所属挑战课程')),
                ('language', models.ForeignKey(help_text='语言', on_delete=django.db.models.deletion.CASCADE, to='sport.LanguageBase', verbose_name='语言')),
            ],
            options={
                'verbose_name': '挑战课程多语言',
                'verbose_name_plural': '挑战课程多语言',
                'db_table': 'sport_language_challenge',
            },
        ),
        migrations.CreateModel(
            name='LanguageProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programName', models.CharField(default='', help_text='课程名称', max_length=100, verbose_name='课程名称')),
                ('programDesc', models.TextField(default='', help_text='课程描述', verbose_name='课程描述')),
                ('language', models.ForeignKey(help_text='语言', on_delete=django.db.models.deletion.CASCADE, to='sport.LanguageBase', verbose_name='语言')),
                ('program', models.ForeignKey(help_text='所属课程', on_delete=django.db.models.deletion.CASCADE, to='sport.Program', verbose_name='所属课程')),
            ],
            options={
                'verbose_name': '课程多语言',
                'verbose_name_plural': '课程多语言',
                'db_table': 'sport_language_program',
            },
        ),
        migrations.AddField(
            model_name='languageaction',
            name='language',
            field=models.ForeignKey(help_text='语言', on_delete=django.db.models.deletion.CASCADE, to='sport.LanguageBase', verbose_name='语言'),
        ),
    ]
