# Generated by Django 2.0.8 on 2019-01-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='languagebase',
            options={'verbose_name': '多语言及json', 'verbose_name_plural': '多语言及json'},
        ),
        migrations.AddField(
            model_name='challenge',
            name='chargeType',
            field=models.IntegerField(choices=[(0, '免费'), (1, '播放课程观看视频'), (2, '进入课程收费')], default=0, help_text='付费类型', verbose_name='付费类型'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='slotid',
            field=models.IntegerField(default=0, help_text='广告id', verbose_name='广告id'),
        ),
        migrations.AddField(
            model_name='program',
            name='slotid',
            field=models.IntegerField(default=0, help_text='广告id', verbose_name='广告id'),
        ),
        migrations.AlterField(
            model_name='program',
            name='chargeType',
            field=models.IntegerField(choices=[(0, '免费'), (1, '播放课程观看视频'), (2, '进入课程收费')], default=0, help_text='付费类型', verbose_name='付费类型'),
        ),
    ]
