# Generated by Django 2.0.8 on 2019-01-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_languagebase_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagebase',
            name='version',
            field=models.BigIntegerField(default=0, help_text='版本', verbose_name='版本'),
        ),
    ]
