# Generated by Django 2.0.8 on 2018-12-17 14:27

import XServer.settings
from django.db import migrations, models
import sport.models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0004_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(help_text='图片', storage=XServer.settings.ImageStorage(), upload_to=sport.models.Image.get_photo_path, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='image',
            name='imgType',
            field=models.IntegerField(choices=[(1, '普通封面图'), (2, '视频封面')], default=1, help_text='图片类型', verbose_name='图片类型'),
        ),
        migrations.AlterField(
            model_name='program',
            name='imgCover',
            field=models.CharField(blank=True, default='', help_text='封面图', max_length=200, null=True, verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='program',
            name='imgCoverBig',
            field=models.CharField(blank=True, default='', help_text='封面大图', max_length=200, null=True, verbose_name='封面大图'),
        ),
        migrations.AlterField(
            model_name='program',
            name='programDesc',
            field=models.TextField(blank=True, default='', help_text='课程描述', null=True, verbose_name='课程描述'),
        ),
        migrations.AlterField(
            model_name='program',
            name='restIndexArray',
            field=models.CharField(blank=True, default='', help_text='休息Index', max_length=100, null=True, verbose_name='休息Index'),
        ),
    ]
