# Generated by Django 2.0.8 on 2018-12-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='名称')),
                ('moblie', models.CharField(max_length=11, verbose_name='电话')),
            ],
        ),
    ]
